# Secret Scanning for repository using trufflehog
# Maintainer: Tim Jonas Meinerzhagen (GHXAX)

name: Secret Scanning
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  trufflehog:
    name: Trufflehog 
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: cleanup permissions #https://github.com/actions/checkout/issues/273
        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - uses: max/secret-scan@956b815c9acb5cf317c11b367920090f09090073
