# Secret Scanning for repository using trufflehog
# Maintainer: Tim Jonas Meinerzhagen (GHXAX)

name: Secret Scanning
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  trufflehog:
    name: Trufflehog Scan
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: max/secret-scan@04dbad7694a0b9582cb6864f98349f728582d7ea
