
# Generic workflow for usage of SonarQube with Bayer SonarQube
# Maintainer: Tim Jonas Meinerzhagen (GHXAX)
#
# Prerequisites: Needs SONAR_TOKEN to be present in Secrets Environemnt

name: SonarQube
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.1.0
        with:
          host: "https://sonar-github.cloud.bayer.com"
          login: ${{ secrets.SONAR_TOKEN }}